### ISSUE TITLE
Change / contextualise z-curve (particularly observed discovery rate)

### ISSUE THREAD

**Issue by LukasWallrich** [forrtproject/FReD#2]
z-curve intends to explore whether a set of effect sizes is selected for significance -  but here, it comes as no surprise that replication targets are selected for significance. So, do we need to make it more explicit how this can be interpreted here? Also, add link to z-curve article?

**Comment by LukasRoeseler** [comment]
I added the link to the z-curve paper to the citation - or did you mean the pre-print using z-curve on the entire database (https://osf.io/preprints/metaarxiv/ewb2t)? 

Updated text:

<i>Note. </i>Z-curve (<a href='http://dx.doi.org/10.15626/MP.2021.2720'>Bartos & Schimmack, 2020</a>) can be used to estimate replicability of a set of studies. Note that it assumes that observations are independent, which is not the case here, and that it uses only significant results. We recommend not using z-curve on less than 200 tests.<br/>Observed discovery rate refers to the proportion of significant (p < .05) studies. Expected discovery rate is the proportion of studies that you would expect to be significant if you ran perfect and high powered replications of <i>all</i> studies. Expected replicability rate is the proportion of studies that you would expect to be significant if you ran perfect and high powered replications of <i>all significant</i> studies. You can compare the discovery and replicability rates with the actual replicability presented at the top of this page. We recommend running bootstraps to get confidence intervals for z-curve's estimates but refrain from doing so as it takes much time.
